# ==============================================================================
# ARQUIVO: .streamlit/config.toml
# DESCRIÇÃO: Configurações do tema visual da aplicação.
# ==============================================================================
[theme]
# Cor primária para elementos interativos (botões, sliders, etc.)
primaryColor="#fecb00"

# Cor de fundo principal da aplicação
backgroundColor="#002776"

# Cor de fundo secundária (barra lateral, fundo de widgets)
secondaryBackgroundColor="#009c3b"

# Cor do texto principal
textColor="#FFFFFF"

# Família da fonte a ser usada
font="sans serif"